### ISSUE TITLE
Create new react admin resource for error type

### ISSUE THREAD

**Issue by petmongrels** [avniproject/integration-admin-app#3]
1. Ability to view all error types, create new error types and edit error type.
2. Use of error type in filters of error record listing (note there is no credit/edit for error record because they are created by the integration process)

**Comment by himeshr** [comment]
Code changes made as part of commit [68440182b3437435b62494fe62c8cd960c6f651a](https://github.com/avniproject/integration-admin-app/commit/68440182b3437435b62494fe62c8cd960c6f651a)
